payplug/payplug-woocommerce

package-lock.json, package.json
fix 84 high severity vulnerabilities
#62
=> fix (npm) : audit fix

composer.json, composer.lock
Update composer packages to get last version of vendor for :
- payplug/payplug-php
- composer/installers
=> Dan composer

payplug.php, readme.txt
Update readme.txt and version showed
=> Release - 1.1.0 (official)

src/Gateway/PayplugApi.php, src/Gateway/PayplugGatewayOney3x.php, src/PayplugWoocommerceHelper.php
Correctif Oney + Correctif rebase
=> Develop use pr

assets/css/payplug-oney.css, assets/js/payplug-oney.js, src/Front/PayplugOneyDetail.php
=> WOOC-148 - Modif affichage popup page produit

src/Gateway/PayplugGatewayOney3x.php, src/Gateway/PayplugGatewayOney4x.php
=> Fix before PR

assets/js/payplug-oney.js
=> Fix PR Daniel

src/Gateway/PayplugGatewayOney3x.php
=> Fix error PR sur l'installation

assets/css/payplug-oney.css
=> Wooc-141 fix CSS

assets/js/payplug-oney.js, src/Front/PayplugOneyDetail.php, src/Gateway/PayplugGatewayOney3x.php, src/PayplugWoocommerceHelper.php
=> Wooc - 146 - Fix product quantity max & popup

src/Gateway/PayplugAddressData.php
=> Correction concaténation php

assets/js/payplug-oney.js, languages/payplug-fr_FR.po, languages/payplug-it_IT.po, languages/payplug.pot, src/Front/PayplugOneyDetail.php, src/Gateway/PayplugAddressData.php, src/Gateway/PayplugGatewayOney3x.php
=> fix-pr-wooc141-146

assets/js/payplug-oney.js
=> fix-dan-pr-condition-oney

.github/pull_request_template.md, payplug.php, src/Gateway/PayplugGatewayOney3x.php
=> ajout contrôle pays sur les deux adresses

assets/js/payplug-oney.js, payplug.php, src/Front/PayplugOneyDetail.php
=> WooC-146-fix

README.md, payplug.php, readme.txt
=> Readme 1.2.0

payplug.php, src/Front/PayplugOneyDetail.php
=> wooc-165 - Fix call getAccount

src/Gateway/PayplugGatewayOney3x.php, src/PayplugWoocommerceHelper.php
=> Changement du comportement du getAccount avec un transient

src/Gateway/PayplugGatewayOney3x.php
=> Suppression de la fonction getkey obsolète

payplug.php, readme.txt
=> Test last version

payplug.php, readme.txt, src/Front/PayplugOneyDetail.php, src/Gateway/PayplugGatewayOney3x.php, src/PayplugWoocommerceHelper.php
=> Release 1.2.3

src/Front/PayplugOneyDetail.php
=> WOOC-166 : Coût financement divisé par 100

src/Front/PayplugOneyDetail.php
=> Develop wooc 169

payplug.php, src/Front/PayplugOneyDetail.php
=> WOOC-166 / WOOC-169

src/Gateway/PayplugResponse.php, src/PayplugWoocommerceHelper.php
=> SIM-574 - Correction pb double flux IPN en simultanée sur Oney

src/Gateway/PayplugResponse.php, src/PayplugWoocommerceHelper.php
=> Develop sim 586 (erreur dans le nom du commit, c'est bien le ticket 586 et pas 587)

payplug.php, readme.txt
=> PR SIM-574 / 587

assets/css/payplug-oney.css, assets/js/payplug-oney.js, payplug.php, src/Front/PayplugOneyDetail.php
=> Wooc 170 close popup oney

payplug.php, src/Gateway/PayplugGatewayRequirements.php
=> FIX SIM-621, namespace

payplug.php, readme.txt
=> Update readme.txt and version for Release 1.2.4

assets/css/payplug-oney.css, assets/js/payplug-oney.js, payplug.php, src/Front/PayplugOneyDetail.php
=> WOOC-162 - Suppression flèche

assets/js/payplug-admin.js, package-lock.json, payplug.php, src/Gateway/PayplugGateway.php, src/Gateway/PayplugGatewayOney3x.php
=> WOOC-162 / WOOC-181 / WOOC-168 / WOOC-183 / WOOC-182

assets/js/payplug-admin.js, package-lock.json, payplug.php, readme.txt, src/Gateway/PayplugGateway.php, src/Gateway/PayplugGatewayOney3x.php
=> Release 1.2.7

src/PayplugWoocommerceHelper.php
=> WOOC-194, fix condition isset

README.md, readme.txt
=> WOOC-192 : Update link for our features

assets/js/payplug-admin-oney.js, payplug.php, src/Gateway/PayplugGateway.php, src/Gateway/PayplugGatewayRequirements.php, src/PayplugWoocommerceHelper.php
=> Wooc-194 Suppression des CGV Oney

composer.lock, payplug.php, src/Gateway/PayplugApi.php
=> WOOC-240 fix user agent

payplug.php, src/Gateway/PayplugGateway.php
=> WOOC-239 : Fix erreur if

src/Gateway/PayplugGatewayOney3x.php
=> WOOC-310 remove type declaration for php5.6 support

payplug.php, readme.txt
=> Update version and add changelog

composer.json, composer.lock
=> update composer files

src/PayplugWoocommerce.php
=> WOOC-350 remove unneeded code

assets/js/payplug-admin-oney.js, readme.txt
=> merge for release

src/Front/Layout/OneyBase.php, src/PayplugWoocommerce.php
=> Failsafe proposal

src/PayplugWoocommerceHelper.php
=> SMP-405 - add Exception

payplug.php, readme.txt, src/Controller/Bancontact.php
=> WOOC-367 update version/changelog + fix for bancontact auth

src/Gateway/PayplugGateway.php, src/Gateway/PayplugResponse.php
=> SMP-645 - Fix missing IPN requests, removing bugfix for repetition logs

readme.txt
=> Fix readme.txt

payplug.php, readme.txt, src/Controller/ApplePay.php, src/Controller/Bancontact.php, src/Gateway/PayplugGateway.php, src/Gateway/PayplugGatewayOney3x.php, src/Gateway/PayplugResponse.php
=> qa to master

payplug.php, readme.txt
=> WOOC-473 : Update WC version

src/Gateway/PayplugGateway.php
Reverts payplug/payplug-woocommerce#587
=> Revert "WOOC-833 : change the API initialisation on payment"

src/Gateway/PayplugGateway.php, src/Gateway/PayplugGatewayOney3x.php
This reverts commit 69eaa10422827408bc37b71d852cec756c9396a8.
=> SMP-1363 : Fix errors

src/Gateway/Blocks/PayplugGenericBlock.php
Payment by saved card activated even if the amount exceeds 20,000 (limit), on blocks only
=> PRE-2947 : fix display saved cards for unauthorized amounts
